// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxELcvaAiKYogPbxN1SX3D8S3wPZML8ng',
    appId: '1:698664129056:web:36e915fa6b60c512e5a245',
    messagingSenderId: '698664129056',
    projectId: 'ecommerce-flutter-22e70',
    authDomain: 'ecommerce-flutter-22e70.firebaseapp.com',
    storageBucket: 'ecommerce-flutter-22e70.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTWG5k7HRxNU1NJ7FaULi4Eb4rIgbRjCw',
    appId: '1:698664129056:android:6bb5d16f75d827e8e5a245',
    messagingSenderId: '698664129056',
    projectId: 'ecommerce-flutter-22e70',
    storageBucket: 'ecommerce-flutter-22e70.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6nobR4nK_uGsbV5VdbWfWdKsvvxz81DI',
    appId: '1:698664129056:ios:916a32841583f4c3e5a245',
    messagingSenderId: '698664129056',
    projectId: 'ecommerce-flutter-22e70',
    storageBucket: 'ecommerce-flutter-22e70.appspot.com',
    iosBundleId: 'com.example.ecommerceFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6nobR4nK_uGsbV5VdbWfWdKsvvxz81DI',
    appId: '1:698664129056:ios:916a32841583f4c3e5a245',
    messagingSenderId: '698664129056',
    projectId: 'ecommerce-flutter-22e70',
    storageBucket: 'ecommerce-flutter-22e70.appspot.com',
    iosBundleId: 'com.example.ecommerceFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAxELcvaAiKYogPbxN1SX3D8S3wPZML8ng',
    appId: '1:698664129056:web:f73415cd8ceb7041e5a245',
    messagingSenderId: '698664129056',
    projectId: 'ecommerce-flutter-22e70',
    authDomain: 'ecommerce-flutter-22e70.firebaseapp.com',
    storageBucket: 'ecommerce-flutter-22e70.appspot.com',
  );
}
